# PRACTICAL COMPUTING
## Python in Jupyter
### Lists and Tuples Finishing

In [6]:
mylist = [1,2,3,4,5]

mylist

[1, 2, 3, 4, 5]

In [7]:
mylist.append (6)

mylist

[1, 2, 3, 4, 5, 6]

In [8]:
mytuple = (1,2,3,4,5)

mytuple

(1, 2, 3, 4, 5)

In [9]:
mytuple.append (6)

AttributeError: 'tuple' object has no attribute 'append'

### Libraries ("Modules" or in R parlance packages)

In [4]:
import os

In [5]:
os. listdir()

['.DS_Store',
 'environment.yml',
 'Untitled.ipynb',
 'README.md',
 'scripts',
 'PracComp_Data4BashExample.zip',
 '.ipynb_checkpoints',
 '.git',
 'MarkdownTutorial.md',
 'data']

In [2]:
import pandas as pd

In [10]:
surveys_df = pd.read_csv("data/portal-teachingdb-master/surveys.csv")

In [11]:
surveys_df

,record_id,month,day,year,plot_id,species_id,sex,hindfoot_length,weight
0,1,7,16,1977,2,NL,M,32.0,NaN
1,2,7,16,1977,3,NL,M,33.0,NaN
2,3,7,16,1977,2,DM,F,37.0,NaN
3,4,7,16,1977,7,DM,M,36.0,NaN
4,5,7,16,1977,3,DM,M,35.0,NaN
...,...,...,...,...,...,...,...,...,...
35544,35545,12,31,2002,15,AH,NaN,NaN,NaN
35545,35546,12,31,2002,15,AH,NaN,NaN,NaN
35546,35547,12,31,2002,10,RM,F,15.0,14.0
35547,35548,12,31,2002,7,DO,M,36.0,51.0
35548,35549,12,31,2002,5,NaN,NaN,NaN,NaN

In [13]:
surveys_df.head()

,record_id,month,day,year,plot_id,species_id,sex,hindfoot_length,weight
0,1,7,16,1977,2,NL,M,32.0,NaN
1,2,7,16,1977,3,NL,M,33.0,NaN
2,3,7,16,1977,2,DM,F,37.0,NaN
3,4,7,16,1977,7,DM,M,36.0,NaN
4,5,7,16,1977,3,DM,M,35.0,NaN

In [14]:
type(surveys_df)

pandas.core.frame.DataFrame

In [15]:
surveys_df.dtypes

record_id            int64
month                int64
day                  int64
year                 int64
plot_id              int64
species_id          object
sex                 object
hindfoot_length    float64
weight             float64
dtype: object

In [16]:
pd.unique(surveys_df['species_id'])

array(['NL', 'DM', 'PF', 'PE', 'DS', 'PP', 'SH', 'OT', 'DO', 'OX', 'SS',
       'OL', 'RM', nan, 'SA', 'PM', 'AH', 'DX', 'AB', 'CB', 'CM', 'CQ',
       'RF', 'PC', 'PG', 'PH', 'PU', 'CV', 'UR', 'UP', 'ZL', 'UL', 'CS',
       'SC', 'BA', 'SF', 'RO', 'AS', 'SO', 'PI', 'ST', 'CU', 'SU', 'RX',
       'PB', 'PL', 'PX', 'CT', 'US'], dtype=object)

In [23]:
surveys_df[['species_id', 'weight']]

      species_id  weight
0             NL     NaN
1             NL     NaN
2             DM     NaN
3             DM     NaN
4             DM     NaN
...          ...     ...
35544         AH     NaN
35545         AH     NaN
35546         RM    14.0
35547         DO    51.0
35548        NaN     NaN

[35549 rows x 2 columns]

In [25]:
surveys_df["weight"].describe()

count    32283.000000
mean        42.672428
std         36.631259
min          4.000000
25%         20.000000
50%         37.000000
75%         48.000000
max        280.000000
Name: weight, dtype: float64

In [26]:
surveys_df["weight"].mean()

42.672428212991356

In [29]:
grouped_data = surveys_df.groupby('sex')

In [32]:
grouped_data.describe()

    record_id                                                               \
        count          mean           std  min      25%      50%       75%
sex
F     15690.0  18036.412046  10423.089000  3.0  8917.50  18075.5  27250.00
M     17348.0  17754.835601  10132.203323  1.0  8969.75  17727.5  26454.25

                month            ... hindfoot_length         weight  \
         max    count      mean  ...             75%   max    count
sex                              ...
F    35547.0  15690.0  6.587253  ...            36.0  64.0  15303.0
M    35548.0  17348.0  6.396184  ...            36.0  58.0  16879.0


          mean        std  min   25%   50%   75%    max
sex
F    42.170555  36.847958  4.0  20.0  34.0  46.0  274.0
M    42.995379  36.184981  4.0  20.0  39.0  49.0  280.0

[2 rows x 56 columns]

In [33]:
grouped_data.mean(numeric_only=True)

,record_id,month,day,year,plot_id,hindfoot_length,weight
sex,,,,,,,
F,18036.412046,6.587253,15.880943,1990.644997,11.440854,28.836780,42.170555
M,17754.835601,6.396184,16.078799,1990.480401,11.098282,29.709578,42.995379

In [34]:
surveys_df.groupby('species_id')['record_id'].count()

species_id
AB      303
AH      437
AS        2
BA       46
CB       50
CM       13
CQ       16
CS        1
CT        1
CU        1
CV        1
DM    10596
DO     3027
DS     2504
DX       40
NL     1252
OL     1006
OT     2249
OX       12
PB     2891
PC       39
PE     1299
PF     1597
PG        8
PH       32
PI        9
PL       36
PM      899
PP     3123
PU        5
PX        6
RF       75
RM     2609
RO        8
RX        2
SA       75
SC        1
SF       43
SH      147
SO       43
SS      248
ST        1
SU        5
UL        4
UP        8
UR       10
US        4
ZL        2
Name: record_id, dtype: int64

In [35]:
surveys_df.groupby('species_id')['record_id'].count()['AB']

303

In [36]:
surveys_df['weight']**2

0           NaN
1           NaN
2           NaN
3           NaN
4           NaN
          ...
35544       NaN
35545       NaN
35546     196.0
35547    2601.0
35548       NaN
Name: weight, Length: 35549, dtype: float64